services:
  - type: web
    name: teen-translator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
